version: '3'
services:

  mysql:
    image: "mysql:5.7.10"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "userdev"
      MYSQL_PASSWORD: "superpassSecret78398213719"
      MYSQL_DATABASE: "workeezy"
